services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POETRY_INSTALL_ARGS=--extras cuda128
    environment:
      - LOG_LEVEL=INFO
      - DEVICE=cuda
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - MODEL_IDLE_TIMEOUT=60
      - EMBEDDING_MODEL_NAME=BAAI/bge-m3
      - USE_FP16=false
    ports:
      - "8007:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
