services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POETRY_INSTALL_ARGS=--extras cpu
    environment:
      - LOG_LEVEL=INFO
      - DEVICE=cpu
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - MODEL_IDLE_TIMEOUT=60
      - EMBEDDING_MODEL_NAME=BAAI/bge-m3
    ports:
      - "8007:8000"
    volumes:
      - ./volume/downloaded_embedding_models:/app/downloaded_embedding_models
