name: deploy-docker-image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:  
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [cpu, gpu]
        include:
          - variant: cpu
            build-args: "POETRY_INSTALL_ARGS=--extras cpu"
            tags: |
              ggwozdz/embed-api:cpu-${{ github.ref_name }}
              ggwozdz/embed-api:cpu-latest
          - variant: gpu
            build-args: "POETRY_INSTALL_ARGS=--extras cuda128"
            tags: |
              ggwozdz/embed-api:gpu-${{ github.ref_name }}
              ggwozdz/embed-api:gpu-latest
              ggwozdz/embed-api:${{ github.ref_name }}
              ggwozdz/embed-api:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.variant }}
      uses: docker/build-push-action@v6.10.0
      with:
        push: true
        build-args: |
          ${{ matrix.build-args }}
        labels: |
          org.opencontainers.image.title="Embed API (${{ matrix.variant }})"
          org.opencontainers.image.description="A FastAPI project for generating text embeddings using machine learning models. ${{ matrix.variant == 'gpu' && 'GPU-enabled' || 'CPU-only' }} variant."
          org.opencontainers.image.source="https://github.com/ggwozdz90/embed-api"
          org.opencontainers.image.documentation="https://github.com/ggwozdz90/embed-api/blob/main/docs/README.md"
        tags: ${{ matrix.tags }}

  deploy-dockerhub-overview:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ggwozdz/embed-api
        readme-filepath: ./docs/DOCKERHUB.md
